/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'

const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRoute
  '/products': typeof ProductsRoute
  '/profit': typeof ProfitRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/statements': typeof StatementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRoute
  '/products': typeof ProductsRoute
  '/profit': typeof ProfitRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/statements': typeof StatementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/expenses': typeof ExpensesRoute
  '/invoices': typeof InvoicesRoute
  '/products': typeof ProductsRoute
  '/profit': typeof ProfitRoute
  '/quotations': typeof QuotationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/statements': typeof StatementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/products'
    | '/profit'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/statements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/products'
    | '/profit'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/statements'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/products'
    | '/profit'
    | '/quotations'
    | '/reports'
    | '/settings'
    | '/statements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  ExpensesRoute: typeof ExpensesRoute
  InvoicesRoute: typeof InvoicesRoute
  ProductsRoute: typeof ProductsRoute
  ProfitRoute: typeof ProfitRoute
  QuotationsRoute: typeof QuotationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StatementsRoute: typeof StatementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  ExpensesRoute: ExpensesRoute,
  InvoicesRoute: InvoicesRoute,
  ProductsRoute: ProductsRoute,
  ProfitRoute: ProfitRoute,
  QuotationsRoute: QuotationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StatementsRoute: StatementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
