/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IndexRouteImport } from './routes/index'

const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRoute
  '/profit': typeof ProfitRoute
  '/quotations': typeof QuotationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRoute
  '/profit': typeof ProfitRoute
  '/quotations': typeof QuotationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRoute
  '/profit': typeof ProfitRoute
  '/quotations': typeof QuotationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invoices' | '/profit' | '/quotations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invoices' | '/profit' | '/quotations'
  id: '__root__' | '/' | '/invoices' | '/profit' | '/quotations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvoicesRoute: typeof InvoicesRoute
  ProfitRoute: typeof ProfitRoute
  QuotationsRoute: typeof QuotationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvoicesRoute: InvoicesRoute,
  ProfitRoute: ProfitRoute,
  QuotationsRoute: QuotationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
